# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Ellen Dai
title: Ellen Dai
email: ellenmengdai@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer. Bay Area. Student at Washington University in St. Louis. Me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ellenmdai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  ellenmdai

# change
author: Ellen Dai
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ellenmdai
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/ellen-dai-07667b12a/
pinterest_url:
slack_url:
twitter_url: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Build settings
markdown: kramdown
# remote_theme: andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-feed
sass:
  style: compressed

 # permalink: /blog/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
